POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpbGQxIiwiaWQiOiI1YmRjNWE4NGI2ZTg5ZjI3Y2MwYzlhNTAiLCJpYXQiOjE1NDEyNDUyNzB9.myTpxUC9HOGAsH5eXMmXQxmP9RjB-kx4lRayEhEe0Do

{
    "title": "mul on vaa tokeni middlewarez",
    "author": "juhiD",
    "url": "www.qwerty.com",
    "likes": 666
}